### PR TITLE
fix(codegen): select and input[type=date]

### LINKED ISSUE #78: codegen: input type date is not working
`node lib/cli.js codegen file://$(pwd)/test.html`

```html
<input type="date"/>
```

### LINKED ISSUE #80: codegen cannot use select fields
Cannot select a select option item.

Try it with:
playwright-cli codegen https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes #78
Fixes #80

Hard to test since we can't emulate the OS keyboard events and a select/input[type=date] is in my mind not good testable with our current testing setup. Or what do you think?

### CODE REVIEW

File: src/injected/recorder.ts [hunk 1]
```diff
@@ -155,7 +155,7 @@ export class Recorder {
       return;
     if ((event.target as Element).nodeName === 'INPUT') {
       // Check/uncheck are handled in input.
-      if (((event.target as HTMLInputElement).type || '').toLowerCase() === 'checkbox')
+      if (['checkbox', 'date'].includes(((event.target as HTMLInputElement).type || '').toLowerCase()))
```
Comment (pavelfeldman) [inline src/injected/recorder.ts:158]: Use `shouldIgnoreMouseEvent` from below, then handle check as it used to be

**Review by pavelfeldman — APPROVED** [review]

File: src/injected/recorder.ts (hunk 1 above)
Comment (mxschmitt) [reply src/injected/recorder.ts]: yeah also thought about that. Test broke then didn't do it in the end. Now after adjusting the test to be more realistic, it works.
